/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class AviationCompany extends javax.swing.JFrame {

    /**
     * Creates new form AviationCompany
     */
    public AviationCompany() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CreateNewFlight = new javax.swing.JButton();
        EditFlightInformation = new javax.swing.JButton();
        CreateOffer = new javax.swing.JButton();
        EditOffer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Aviation Company Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 11, -1, -1));

        CreateNewFlight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateNewFlight.setText("Create New Flight");
        getContentPane().add(CreateNewFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 136, 189, -1));

        EditFlightInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditFlightInformation.setText("Edit Flight Information");
        getContentPane().add(EditFlightInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 202, -1, -1));

        CreateOffer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateOffer.setText("Create Offer");
        getContentPane().add(CreateOffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 136, 189, -1));

        EditOffer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditOffer.setText("Edit Offer");
        getContentPane().add(EditOffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 202, 189, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Auxilary Support");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 271, 189, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("View Flights");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 271, 189, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aviationCompanyBackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1500, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AviationCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AviationCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AviationCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AviationCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AviationCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewFlight;
    private javax.swing.JButton CreateOffer;
    private javax.swing.JButton EditFlightInformation;
    private javax.swing.JButton EditOffer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
